/* =====================================================
   data.js — 게시판 메타정보 · 초기 게시글 · 댓글 · 채팅 데이터
   ★ 게시글을 추가/수정/삭제하려면 이 파일만 편집하세요.
   ===================================================== */

/* ── 게시판 목록 ─────────────────────────────────────── */
const BOARD_META = {
  hot:     { name: "핫이슈",    desc: "지금 가장 많이 읽히고 이야기되는 글을 모았습니다." },
  free:    { name: "자유게시판", desc: "학교생활과 일상에 관한 다양한 이야기를 자유롭게 나누는 공간입니다." },
  anon:    { name: "익명게시판", desc: "작성자 표시 없이 의견을 나누는 공간입니다. 기본 이용 규칙은 동일합니다." },
  love:    { name: "연애&썰",   desc: "학교생활 속 인간관계와 경험담을 나누는 게시판입니다." },
  dorm:    { name: "기숙사",    desc: "기숙사 생활, 생활 팁, 시설 관련 정보를 공유합니다." },
  exam:    { name: "시험&성적", desc: "시험 일정, 공부법, 과목별 정보와 학습 경험을 나눕니다." },
  club:    { name: "동아리",    desc: "동아리 소개, 모집, 활동 후기와 정보를 모아봅니다." },
  alumni:  { name: "졸업생",    desc: "졸업생들의 학교 이야기와 진로 경험을 공유합니다." },
  inquiry: { name: "문의사항",  desc: "사이트 이용 중 불편한 점이나 운영 관련 문의를 남겨주세요." },
};

/* ── 초기 게시글 ─────────────────────────────────────── */
// ★ 게시글 순서는 이 배열 순서 그대로 고정됩니다.
// ★ horror 필드 설명:
//    "observer" → 로딩 연출 + 갑툭튀
//    "rainbow"  → 풀스크린 블랙 연출
//    "blank"    → 빈 게시글 (수칙 위반 카운트)
//    "author"   → 수칙 위반 카운트
//    "audio"    → 세 번째 녹음 재생 시 수칙 위반

const seedPosts = [
  {
    id: 1,
    board: "free",
    title: "14년 전 한민고에서 사라진 학생 기록… 그런데 오늘 다시 올라왔다",
    author: "한찌.com러",
    date: "2026-08-09 03:27",
    views: 3415,
    comments: 78,
    likes: 231,
    body: `새벽 3시 27분에 작성된 글입니다.

14년 전 삭제된 학생 기록을 찾았다는 내용이 올라왔습니다.
그런데 이상한 점이 있습니다.

게시물의 작성 시간이 현재 시간과 똑같습니다.
그리고 작성자는 이미 졸업한 학생으로 표시되어 있습니다.

댓글을 읽어보지 마세요.
특히 마지막 댓글은 열지 않는 것을 권합니다.`,
    hot: true,
    horror: "rainbow",
  },
  {
    id: 287,
    board: "free",
    title: "안ㄴㅇ << 얘 아이패드 비번 뚫었음 정보공유하러옴ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ",
    author: "한민러()",
    date: "2026-08-08 23:41",
    views: 6877,
    comments: 146,
    likes: 292,
    body: `급함 ㅋㅋ
누가 저번에 아이패드 잠금번호 알려줬던 거 같은데 기억이 안 남.
댓글에 142857이라던데 맞음?`,
  },
  {
    id: 3,
    board: "free",
    title: "observer",
    author: "관리자",
    date: "2026-08-08 02:03",
    views: 6004,
    comments: 79,
    likes: 15,
    body: `observer를 검색한 사람만 볼 수 있는 게시물입니다.

이 게시물은 정상적으로 열리지 않을 수 있습니다.
계속 로딩되더라도 새로고침하지 마세요.`,
    hot: true,
    horror: "observer",
    hiddenUntilSearch: true,
  },
  {
    id: 4,
    board: "free",
    title: "",
    author: "익명",
    date: "2026-08-07 04:11",
    views: 2235,
    comments: 127,
    likes: 457,
    body: " ",
    hot: true,
    horror: "blank",
  },
  {
    id: 9001,
    board: "free",
    title: "절대 삭제하지 마세요 — 녹음 파일 01 / 02 / 03",
    author: "작성자",
    date: "2026-08-06 01:17",
    views: 8912,
    comments: 3,
    likes: 17,
    body: `아래 파일은 사이트 제작자가 남겨둔 테스트 녹음입니다.

※ 녹음 파일은 나중에 직접 교체하세요.
※ 파일 경로는 코드의 audioFiles 배열에서 확인할 수 있습니다.
※ 세 번째 파일은 분위기가 달라야 합니다.`,
    hot: true,
    horror: "audio",
    audioFiles: [
      "assets/horror_ambience.mp3", // ★ 녹음 1 교체 위치
      "assets/unknown_letter.mp3",  // ★ 녹음 2 교체 위치
      "assets/jumpscare.mp3",       // ★ 녹음 3 교체 위치 — 마지막은 이상한 소리/노래
    ],
  },
  {
    id: 9002,
    board: "free",
    title: "작성자가 작성자인 글",
    author: "작성자",
    date: "2026-08-05 00:06",
    views: 1917,
    comments: 6,
    likes: 8,
    body: `작성자입니다.

이 글을 발견했다면 수칙을 이미 한 번 어긴 것입니다.

왜냐하면 이 게시물은 원래 존재하지 않아야 하기 때문입니다.`,
    hot: true,
    horror: "author",
  },
  {
    id: 9101,
    board: "free",
    title: "%@＾$❆한❇민卫학쌩맍을 우1한 만@◌☉쩜ㅎㅐ킹공부법#@ ㅇF ㄴㅓ두 ❶등급 ௗ할 㐃 있ㅇㅓ#♜$❂@!❋",
    author: "익명",
    date: "2026-08-04 02:41",
    views: 9182,
    comments: 31,
    likes: 2,
    body: `제목이 이상하게 보이는 사람은 정상입니다.

내용을 읽으려고 하지 마세요.
페이지가 멈추더라도 창을 닫지 마십시오.`,
    hot: false,
    horror: "rainbow",
  },
  {
    id: 9102,
    board: "free",
    title: "그ㅅㄲ 패드 비번 뭐냐",
    author: "익명",
    date: "2026-08-03 21:16",
    views: 4831,
    comments: 18,
    likes: 24,
    body: `뭐 없나 하고 패드 뒤지니까 비번 걸려있는데.`,
    hot: false,
  },
  {
    id: 9103,
    board: "free",
    title: "책 표지 플라스틱으로도 만드냐",
    author: "익명",
    date: "2026-08-02 19:52",
    views: 3264,
    comments: 12,
    likes: 8,
    body: `책장 만지다가 차가운 거 있어서 일단 튀었는데 뭔지 아는 사람?`,
    hot: false,
  },
  {
    id: 5,
    board: "love",
    title: "00와 00의 연애… 이대로 괜찮은가",
    author: "고양이편",
    date: "2026-08-01 03:57",
    views: 6425,
    comments: 212,
    likes: 458,
    body: "찰리와 쮸쮸는 이전부터 연애 관계였던 고양이들로 아직도 잘 지내고 있어영.",
    hot: true,
  },
  {
    id: 6,
    board: "club",
    title: "CPS 기장과 클리어 기장의 유착관계… 그 진실은?",
    author: "지켜본다",
    date: "2026-07-30 18:33",
    views: 2487,
    comments: 179,
    likes: 30,
    body: "둘은 자율동아리 '왜요'에서 만난 관계로 서로 음악을 공유하는 왜요 단톡방을 함께 사용 중이고 현재 친해지는 관계라고 밝힌 바가 있다.",
    hot: true,
  },
  {
    id: 7,
    board: "club",
    title: "CPS와 폴라리스의 유착관계… 매 기수마다 생긴다는…. 동아리간의 … 00",
    author: "왜요단톡방",
    date: "2026-07-30 07:31",
    views: 1124,
    comments: 51,
    likes: 171,
    body: "네. 그겁니다.",
    hot: true,
  },
  {
    id: 8,
    board: "free",
    title: "한민고 급식실의 칼로리 허위 기재… 이대로 괜찮은가?",
    author: "폴라리스",
    date: "2026-07-29 02:59",
    views: 5034,
    comments: 147,
    likes: 274,
    body: "무려 칼로리의 소수점 14번째 자리를 반올림으로 올려버렸던 사건이다…",
    hot: true,
  },
  {
    id: 9,
    board: "exam",
    title: "미적분 1 서술형, 성적 조작 의혹 받아…. 만점자 없나?",
    author: "급식러",
    date: "2026-07-27 00:34",
    views: 3675,
    comments: 109,
    likes: 58,
    body: "의혹만 있었을 뿐, 정말 어려웠던 거라고 합니다.",
    hot: true,
  },
  {
    id: 10,
    board: "dorm",
    title: "빈번한 기숙사 에어컨 고장으로 고통받는 학생들, 민원 폭주해…",
    author: "수학은어려워",
    date: "2026-07-20 17:39",
    views: 1155,
    comments: 152,
    likes: 190,
    body: "최대한 빠른 시일 내로 고쳐졌다고 합니다.",
    hot: true,
  },
  {
    id: 11,
    board: "free",
    title: "한민고에 비둘기가 없는 이유… 걸생의 00 때문?",
    author: "기숙사생",
    date: "2026-07-20 16:38",
    views: 5316,
    comments: 150,
    likes: 452,
    body: "한민고는 도심과 멀고 자연환경이 좋도록 걸생에서 나서서 지키고 있다. 그렇기에 도심에 주로 분포하는 비둘기보다 다양한 야생 새들이 많이 자리하고 있다.",
    hot: true,
  },
  {
    id: 12,
    board: "free",
    title: "교장실 앞에 죽어있는 개구리 발견… 한민 개구리 슬레이어의 정체?",
    author: "13기익명",
    date: "2026-07-19 08:28",
    views: 2511,
    comments: 197,
    likes: 178,
    body: "자연사. 교장쌤 아님.",
    hot: true,
  },
  {
    id: 13,
    board: "dorm",
    title: "반에서 에어컨 못 틀게 하는 물리쌤… 결국 교장실로 끌려가",
    author: "한찌.com러",
    date: "2026-07-19 07:01",
    views: 1188,
    comments: 55,
    likes: 425,
    body: "지구를 지켰다. 알고보니 참된 교사상 받으러 갔다.",
    hot: false,
  },
  {
    id: 14,
    board: "free",
    title: "13기들의 0000… 이대로 괜찮은가?",
    author: "익명",
    date: "2026-07-17 16:20",
    views: 4416,
    comments: 113,
    likes: 409,
    body: "13기의 급식시간이 계속 늦어지며 급식을 못 먹는 학생들도 있음.. 급식시간.. 이대로 괜찮은가.",
    hot: false,
  },
  {
    id: 15,
    board: "club",
    title: "왜요 기장 알고보니 여자….?",
    author: "관전자",
    date: "2026-07-14 21:48",
    views: 4709,
    comments: 151,
    likes: 391,
    body: "알고보니, 왜요 기장 이 모씨는 알려진 사실과 달리←? 여성을 좋아한다고 밝힌 바가 있다.",
    hot: false,
  },
  {
    id: 16,
    board: "free",
    title: "시계 실종사건… 목격자들의 증언으로 한 학생이 특정돼…",
    author: "Beta",
    date: "2026-07-13 23:10",
    views: 6148,
    comments: 195,
    likes: 395,
    body: "베개 뒤 시계로 실제 범인임이 드러났다고 밝혀져.",
    hot: false,
  },
  {
    id: 17,
    board: "club",
    title: "TAP 기장과 CPS 기장, 그 비밀스러운 연애관계의 진실",
    author: "고양이편",
    date: "2026-07-12 22:29",
    views: 5696,
    comments: 18,
    likes: 46,
    body: "네 제 여친입니다) – 제 여친인데 이거 정정하시죠.",
    hot: false,
  },
  {
    id: 18,
    board: "free",
    title: "한비제의 비밀… 베타가 숨기고 있는 그것은 무엇인가",
    author: "지켜본다",
    date: "2026-07-11 23:40",
    views: 3173,
    comments: 48,
    likes: 32,
    body: "한비제의 컨셉은 작년의 여행 테마를 벗어나기 위해 노력한 결과로 많은 베타들이 갈려나갔다고 한다.",
    hot: false,
  },
  {
    id: 19,
    board: "club",
    title: "한민고 대표 동아리 PEBC 담당교사, 김태호. 사실 걸생에 더 큰 애착 있는 걸로 알려져…",
    author: "왜요단톡방",
    date: "2026-07-09 08:15",
    views: 3465,
    comments: 179,
    likes: 460,
    body: "한민고 대표 동아리 펩시의 담당교사 김태호와 동명이인인 김태호가 걸생의 기장으로서 펩시보다 걸생을 아끼고 있다고 밝혔다. 걸생의 기장은 매일 열심히 뛰어다니며 걸생의 인원을 모을 정도로 애착이 깊은 것으로 유명하다.",
    hot: false,
  },
  {
    id: 20,
    board: "club",
    title: "인테그랄… 알고보니 정식 과학 동아리?",
    author: "폴라리스",
    date: "2026-07-09 01:04",
    views: 3307,
    comments: 150,
    likes: 179,
    body: "네 맞습니다. 인테그랄은 과학동아리입니다.",
    hot: false,
  },
  {
    id: 21,
    board: "free",
    title: "한민고의 택배가 사라지지 않는 이유… 000으로 밝혀져…",
    author: "급식러",
    date: "2026-07-05 13:08",
    views: 5785,
    comments: 152,
    likes: 20,
    body: "한민고의 택배가 사라지지 않는 이유는 아직 본인의 택배를 가져가지 않는 사람들이 많기에 그렇다. 사감선생님들의 걱정이 크다고 한다.",
    hot: false,
  },
  {
    id: 22,
    board: "club",
    title: "왜요에 모집 비리가 있다? CPS와 관계 있어",
    author: "수학은어려워",
    date: "2026-07-03 12:04",
    views: 7022,
    comments: 79,
    likes: 359,
    body: "왜요 창시 당시 CPS에 가장 먼저 홍보함. 그냥 CPS에 서브컬쳐에 관심 많은 사람이 많아서.",
    hot: false,
  },
  {
    id: 23,
    board: "free",
    title: "급식실 두쫀쿠 실종 사건… 내부자 소행 가능성 높아",
    author: "기숙사생",
    date: "2026-06-28 19:43",
    views: 2808,
    comments: 61,
    likes: 182,
    body: "목격자에 따르면 배식 30분 만에 전부 소진되었다고 한다.",
    hot: false,
  },
  {
    id: 24,
    board: "free",
    title: "한민고, 학생들 몰래 5층 만들다 적발",
    author: "13기익명",
    date: "2026-06-25 19:28",
    views: 8078,
    comments: 45,
    likes: 162,
    body: "한민고 계단이 열심히 계단을 오르는 학생들을 놀리기 위해 은근슬쩍 층고수를 높이다 적발되었다. 이에 학생들은 '왠지 계단이 많더라', '앞으로 엘베만 탄다' 등의 반응을 보이고 있다. 불법 증축된 계단의 블럭수는 총 10개. 수정해야함.",
    hot: false,
  },
  {
    id: 25,
    board: "free",
    title: "한민고 연못에 뛰어든 걸생의 유 모군… 그의 행방은?",
    author: "한찌.com러",
    date: "2026-06-25 01:52",
    views: 5537,
    comments: 163,
    likes: 469,
    body: "한민고 연못의 수질오염을 걱정한 유 모군은 과학과제연구 탐구주제로 생물활성탄을 만들고자 하였다. 앞으로 연구가 어떻게 진행되는지가 기대되는 바이다.",
    hot: false,
  },
  {
    id: 26,
    board: "club",
    title: "가장 강력한 동아리라고 주장하는 000",
    author: "익명",
    date: "2026-06-24 20:46",
    views: 1961,
    comments: 203,
    likes: 208,
    body: "정체는 아직 밝혀지지 않았다.",
    hot: false,
  },
  {
    id: 27,
    board: "free",
    title: "최근 와이파이 품질 저하의 이유, 한민고에서 예산 줄이려고….",
    author: "관전자",
    date: "2026-06-21 13:10",
    views: 1251,
    comments: 78,
    likes: 410,
    body: "선생님들이 와이파이를 다 쓰고 있다는 소문이 돌고 있다.",
    hot: false,
  },
  {
    id: 28,
    board: "club",
    title: "엠퍼런스가 원래 없었던 동아리라고??..",
    author: "Beta",
    date: "2026-06-15 11:27",
    views: 2139,
    comments: 52,
    likes: 143,
    body: "엠퍼런스는 없고 엠퍼러스에요.",
    hot: false,
  },
  {
    id: 29,
    board: "free",
    title: "한민고 급식먹고 구토한 학생… 한민고 급식, 이대로 괜찮은가..?",
    author: "고양이편",
    date: "2026-06-07 05:31",
    views: 7401,
    comments: 26,
    likes: 140,
    body: "독감 때문에 고열로 인한 증상이었답니다.",
    hot: false,
  },
  {
    id: 30,
    board: "free",
    title: "어디에도 기재되지 않은 '업로드'... 실존 가능성은?",
    author: "지켜본다",
    date: "2026-06-06 20:12",
    views: 2510,
    comments: 103,
    likes: 378,
    body: "있'었'습니다. 2025년에 만들어져서 1년 만에 증발함. 있었는데요 없었습니다.",
    hot: false,
  },
  {
    id: 31,
    board: "free",
    title: "한민고 깨진 유리창… 총기 사용 의혹.. 곧 북한 내려오나..",
    author: "왜요단톡방",
    date: "2026-06-06 11:06",
    views: 1900,
    comments: 135,
    likes: 387,
    body: "이 모씨가 야구공을 이용해 강속구로 깨부신 거라고 하네요.",
    hot: false,
  },
  {
    id: 32,
    board: "free",
    title: "한민고 지하의 비밀: 120인의 방공호",
    author: "폴라리스",
    date: "2026-05-31 17:35",
    views: 2401,
    comments: 57,
    likes: 131,
    body: "한민고는 군자녀 대상 고등학교로 설립 이래부터 조국수호의 의지를 다져왔다. 때문에 유사시 상황을 대비하여 지하에 최대 120명까지 수용 가능한 방공호를 만들어두었다고 한다. 수정해야함.....?",
    hot: false,
  },
  {
    id: 33,
    board: "free",
    title: "주차장에 있는 피묻은 벽돌이 발견돼… 타살 가능성?",
    author: "급식러",
    date: "2026-05-30 11:53",
    views: 3690,
    comments: 28,
    likes: 367,
    body: "사실 피가 아니라 촬영용으로 칠한 마카라고 하네요.",
    hot: false,
  },
  {
    id: 34,
    board: "free",
    title: "한민고 도서관 이름이 '규장각'인 이유… 군사시설, '장용영'",
    author: "수학은어려워",
    date: "2026-05-27 13:30",
    views: 7268,
    comments: 47,
    likes: 117,
    body: "이름을 둘러싼 학교식 패러디 기사입니다.",
    hot: false,
  },
  {
    id: 35,
    board: "free",
    title: "한민고에서 출판한 [한민고 이야기] 판매 수 조작 의혹 생겨",
    author: "기숙사생",
    date: "2026-05-27 13:17",
    views: 742,
    comments: 108,
    likes: 152,
    body: "한민고 이야기 독후감이 방학 숙제였다고 하네요.",
    hot: false,
  },
  {
    id: 36,
    board: "free",
    title: "일산화이수소 위험성 논란 재조명… 한민고에서 한 학생의 언급. 염산보다 높은 pH인데 상용화되어도 괜찮은가",
    author: "13기익명",
    date: "2026-05-24 03:11",
    views: 1283,
    comments: 142,
    likes: 468,
    body: "일산화이수소는 물입니다. 네, 물이요. H2O. pH는 작을수록 산이 강합니다.",
    hot: false,
  },
  {
    id: 37,
    board: "exam",
    title: "신청자 적은 과목 선택 이유, 알고보니 합반?",
    author: "한찌.com러",
    date: "2026-05-23 05:17",
    views: 2683,
    comments: 66,
    likes: 107,
    body: "합반 가고 싶어서 고급 화학 선택했는데 안 됐대요 …?",
    hot: false,
  },
  {
    id: 38,
    board: "free",
    title: "운돌했다는 사실만으로 공격받아, 물리적 피해 없이도 정신적 피해 남겨….",
    author: "익명",
    date: "2026-05-20 00:56",
    views: 3441,
    comments: 57,
    likes: 215,
    body: "얼레리꼴레리 친구들이 놀려요 ㅋ",
    hot: false,
  },
  {
    id: 39,
    board: "free",
    title: "바다의 생명체들과 한민고의 '운돌' 문화",
    author: "관전자",
    date: "2026-05-19 02:20",
    views: 1492,
    comments: 203,
    likes: 251,
    body: "이는 바다에서 나온 물고기를 활용한 회전초밥의 원리와 비슷하다. 중간에 끼어들 수도 있고, 한 방향으로만 돌 수 있다. 정해진 라인을 벗어나지 않고, 그 수는 늘어나거나 줄어든다는 공통점이 있다.",
    hot: false,
  },
  {
    id: 40,
    board: "free",
    title: '12기 최 모군, 정보과 선생님을 향해 "샤갈!" 외쳐… 교권 추락의 진실',
    author: "Beta",
    date: "2026-05-19 02:04",
    views: 6441,
    comments: 172,
    likes: 181,
    body: "친구인 줄 알고 잘못 외쳤고, 평소 존경하던 선생님이라 굉장히 죄송하다고 여기고 있다고 알린 바가 있습니다.",
    hot: false,
  },
  {
    id: 41,
    board: "free",
    title: "한민고 1학년, 코끼리..?",
    author: "고양이편",
    date: "2026-05-18 22:09",
    views: 2030,
    comments: 156,
    likes: 361,
    body: "별명이 코끼리라네요~",
    hot: false,
  },
  {
    id: 42,
    board: "anon",
    title: "남자 혼자 하루에 소개팅 9번… 익명의 위험성",
    author: "익명",
    date: "2026-05-17 11:27",
    views: 5870,
    comments: 139,
    likes: 300,
    body: "2025년 아가판더스 소개팅 부스에서 혼자 부스 9번 돈 사람이 있다고 알려진 바 있다.",
    hot: false,
  },
  {
    id: 43,
    board: "free",
    title: "합반의 짝꿍 운영, 결국은 '이것' 만들어…",
    author: "왜요단톡방",
    date: "2026-05-16 18:47",
    views: 3436,
    comments: 156,
    likes: 401,
    body: "합반의 짝꿍 운영으로 인해 무려 29명이 거주하던 교실에 드디어 통행로가 만들어졌다. 학생들은 매우 만족 중이라고 한다.",
    hot: false,
  },
  {
    id: 44,
    board: "free",
    title: "합반 남자 둘 사이에 여자 자리 앉혀… 여학생 차별?",
    author: "폴라리스",
    date: "2026-05-13 03:07",
    views: 3481,
    comments: 188,
    likes: 193,
    body: "홀수라 3명 앉는 자리가 있는데 랜덤으로 뽑았는데 운이 안 좋은 학생이었다고 하네요.",
    hot: false,
  },
  {
    id: 45,
    board: "free",
    title: "용철공주, 사실은 남자?",
    author: "급식러",
    date: "2026-05-12 03:56",
    views: 2313,
    comments: 47,
    likes: 332,
    body: "용철공주는 다은쌤의 고양이 용철이로 지금은 성별이 없다고 한다.",
    hot: false,
  },
  {
    id: 46,
    board: "free",
    title: "교실에 젓가락 한 쌍 발견… 급식실에서 무단 반출했나…",
    author: "수학은어려워",
    date: "2026-05-09 10:30",
    views: 6767,
    comments: 88,
    likes: 178,
    body: "이 모씨와 이 모씨 두 사람이 너무 가벼워 항상 젓가락 소리를 듣는다고 하네요.",
    hot: false,
  },
  {
    id: 47,
    board: "free",
    title: "합반에서 양다리 걸친 남학생 A… 그 진실은?",
    author: "기숙사생",
    date: "2026-05-08 10:07",
    views: 3602,
    comments: 180,
    likes: 148,
    body: "최 모씨가 의자 두 개를 한 번에 두고 양다리를 걸쳤다고 한다…",
    hot: false,
  },
  {
    id: 48,
    board: "free",
    title: "매점 가격 인상 - 편의점보다 높은 가격으로 학생들 기만하나",
    author: "13기익명",
    date: "2026-05-05 07:07",
    views: 6811,
    comments: 102,
    likes: 140,
    body: "이건.. 실제입니다..",
    hot: false,
  },
  {
    id: 49,
    board: "club",
    title: "한민고 과학 동아리, 9개가 아니라고?",
    author: "한찌.com러",
    date: "2026-05-05 01:58",
    views: 4093,
    comments: 136,
    likes: 432,
    body: "원래 9개였지만 올해 오스가 과동이 되며 10개가 됐답니다.",
    hot: false,
  },
  {
    id: 50,
    board: "exam",
    title: '한민고 수행평가, 형평성 논란? "같은 반인데 수행은 달라요"',
    author: "익명",
    date: "2026-05-04 22:25",
    views: 8433,
    comments: 43,
    likes: 463,
    body: "같은 반이지만 제2외국어가 달라서 수행이 다릅니다.",
    hot: false,
  },
  {
    id: 51,
    board: "free",
    title: "남학생 반에서 여학생 다수 발견…",
    author: "관전자",
    date: "2026-05-02 22:10",
    views: 3507,
    comments: 153,
    likes: 244,
    body: "만우절에 2학년 남자 반이랑 1학년 여자 반이 교실 바꿨답니다.",
    hot: false,
  },
  {
    id: 52,
    board: "anon",
    title: '학생 정 모씨, "난 아빠 덕분에 한민고 입학했다" 발언… 이사장 특혜?',
    author: "익명",
    date: "2026-04-30 17:32",
    views: 2083,
    comments: 196,
    likes: 50,
    body: "아버지께서 이사장님과 동명이인이라 합니다. 아버지께서 군인이신 덕에 군자녀로 왔다네요.",
    hot: false,
  },
  {
    id: 53,
    board: "club",
    title: "한민고 모 동아리에서 000 8명 발각… 무서울 지경",
    author: "고양이편",
    date: "2026-04-29 10:06",
    views: 2813,
    comments: 13,
    likes: 447,
    body: "CPS에서 마니또 8명이 발각됐죠..",
    hot: false,
  },
  {
    id: 54,
    board: "love",
    title: '한민고 내부 교제의 폐해… "내가 더 좋아 쟤가 더 좋아?"',
    author: "지켜본다",
    date: "2026-04-29 08:34",
    views: 4707,
    comments: 78,
    likes: 114,
    body: "룸메들이 장난으로 물어봤다 합니다.",
    hot: false,
  },
  {
    id: 55,
    board: "free",
    title: "한민고 13기, 특정 반만 00 없어… 반 단위 차별?",
    author: "왜요단톡방",
    date: "2026-04-28 05:40",
    views: 6997,
    comments: 95,
    likes: 252,
    body: "한 반만 햇빛이 없습니다..",
    hot: false,
  },
  {
    id: 56,
    board: "free",
    title: '만우절 지나친 장난에 내려진 특단의 조치… "운동장으로 나오세요"',
    author: "폴라리스",
    date: "2026-04-20 23:57",
    views: 1190,
    comments: 147,
    likes: 170,
    body: "운동장 댄스파티 재밌었어요.",
    hot: false,
  },
  {
    id: 57,
    board: "free",
    title: "밤 9시, 운동장 한복판 비명소리의 진실은?",
    author: "급식러",
    date: "2026-04-19 18:44",
    views: 1579,
    comments: 36,
    likes: 97,
    body: "별똥별 떨어졌다네요.",
    hot: false,
  },
  {
    id: 58,
    board: "anon",
    title: "학생 윤 모씨, 도플갱어 발견…?",
    author: "익명",
    date: "2026-04-18 22:26",
    views: 3642,
    comments: 161,
    likes: 469,
    body: "동명이인이라네요~",
    hot: false,
  },
  {
    id: 59,
    board: "free",
    title: "야밤에 내리는 비를 틈 타 나가려다 교문에서 적발되는 사례 증가, 이대로 괜찮은가",
    author: "기숙사생",
    date: "2026-04-16 00:18",
    views: 1664,
    comments: 176,
    likes: 250,
    body: "맹꽁이가 비올 때마다 계속 밖으로 나온대요…ㅜㅜ 걸생이들이 잘 잡아서 호수에 넣어주고 있다고 합니다.",
    hot: false,
  },
  {
    id: 60,
    board: "club",
    title: "CPS, 사실 000을 찬양하는 집단..?",
    author: "13기익명",
    date: "2026-04-15 18:02",
    views: 6328,
    comments: 39,
    likes: 439,
    body: "누가 CPS 보고 Cutie Pretty Sangcheonteacher 아니냐고 하더라고요.",
    hot: false,
  },
  {
    id: 61,
    board: "club",
    title: "동아리의 유령부원 증가 추세… 장 모씨 '항상 주변을 경계할 필요있어'",
    author: "한찌.com러",
    date: "2026-04-15 00:10",
    views: 4970,
    comments: 156,
    likes: 251,
    body: "요즘 동아리에서 부원의 이름은 적혀 있지 않으나 새 동아리 옷을 맞춘 뒤 그 옷과 똑같은 디자인의 옷을 입은 채 배회하는 존재들이 확인되었다. 이 존재들은 새 동아리 옷을 맞추는 시기에 대량으로 발생하는 존재들로, 실제 동아리 부원이 아니나 그 모습과 유사해 착각하기 쉽다… 이들을 보고 주의깊게 생각하고, 경계하지 않을 경우 같은 동아리 선배의 연인에게 인사하는 낯부끄러운 일이 생길 수 있다… 주의하자.",
    hot: false,
  },
  /* ── 퍼즐 관련 게시글 ─────────────────────────────── */
  {
    id: 62,
    board: "anon",
    title: "2학년 15반 걔 과거 아는 사람",
    author: "익명",
    date: "2026-08-09 11:22",
    views: 2847,
    comments: 8,
    likes: 43,
    body: `아니, 2학년 15반에 레전드 하나 들어왔다는데 이름이 뭐더라 하,,, 잘 모르겠는데

쨌든 개학하자마자 반 애들이랑 싸우고 진짜 끝핑 말도 아니었음 진짜 한민 어케 들어옴??`,
    hot: false,
  },
  {
    id: 63,
    board: "free",
    title: "안ㄴㅇ << 얘 아이패드 비번 뚫었음 정보공유하러옴ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ",
    author: "익명",
    date: "2026-08-09 13:04",
    views: 5912,
    comments: 3,
    likes: 87,
    body: `142857이다 이것들아`,
    hot: false,
  },
  {
    id: 64,
    board: "free",
    title: "님들 내가 바로 레전드 책-지피티를 발견해버렸잖아ㅋㅋ",
    author: "익명",
    date: "2026-08-09 16:51",
    views: 1203,
    comments: 2,
    likes: 34,
    body: `챗지피티 아니다 바로 책-지피티라는거다
책은 무엇이든 딱 피면 바로 알려주시잖아
심지어 말이야 어? 면학 3타임때도 당당하게 쓸수있다 이말이야
구라안까고 이게 ㄹㅇ 챗지피티아니냐?`,
    hot: false,
  },
  {
    id: 65,
    board: "club",
    title: "동아리 기장들은 다풀었다는 전설의 문제 지금바로ㄱㄱ",
    author: "익명",
    date: "2026-08-09 20:37",
    views: 3401,
    comments: 2,
    likes: 156,
    body: `이거 풀면 님들도 기장먹기 쌉가능
아 나는 풀었음ㅋ`,
    hot: false,
  },
];

/* ── 초기 댓글 ───────────────────────────────────────── */
// id    : 댓글 고유 번호 (대댓글 연결에 필요)
// parentId : 대댓글일 때 부모 댓글의 id (없으면 생략)
const seedComments = [
  { id: 1, postId: 287,  author: "ㅇㅇ",    text: "야 아이패드 비번 뭐냐?ㅋㅋ 게시물에 댓글로 그거 142857이래", time: "방금 전" },
  { id: 2, postId: 9001, author: "익명",    text: "세 번째 파일만 재생하지 마.",                               time: "1분 전" },
  { id: 3, postId: 1,    author: "ㅇㅇ",    text: "이런 형태 게시판 진짜 오랜만이다",                         time: "2분 전" },
  { id: 4, postId: 9002, author: "관전자",  text: "작성자가 작성자라고?",                                      time: "3분 전" },
  { id: 5, postId: 5,    author: "뉴런123", text: "활동 내용이 동아리마다 꽤 다르더라",                       time: "4분 전" },
  { id: 6, postId: 6,    author: "시간표",  text: "아직 공식 공지는 못 봤어",                                  time: "5분 전" },

  /* ── 62: 2학년 15반 ──────────────────────────────── */
  { id: 7,  postId: 62,                   author: "익명", text: "걔 유명하자나 ㅇㄴㅇ(안노운) 아니야",                                                       time: "1시간 전"  },
  { id: 8,  postId: 62, parentId: 7,      author: "익명", text: "어어 맞는 것 같으",                                                                           time: "58분 전"   },
  { id: 9,  postId: 62, parentId: 7,      author: "익명", text: "아니ㅋㅋㅋ 그 사람의 이름을 말해선 안돼",                                                     time: "55분 전"   },
  { id: 10, postId: 62, parentId: 9,      author: "익명", text: "왜 뭐 ㅂㅌㅁㅌ 그런거임? <<<이거 설마 볼드모트? ㅋㅋㅋㅋㅋ",                                  time: "52분 전"   },
  { id: 11, postId: 62, parentId: 7,      author: "익명", text: "…? 걔 입학식날에 앞에서 상 받았던애아님? 아니 ㄹㅇ?",                                         time: "50분 전"   },
  { id: 12, postId: 62, parentId: 11,     author: "익명", text: "인성 안보고 숫자로 들어오잖음 수행평가 꿰메기는 잘했나보지뭐ㅋㅋㅋㅋ",                         time: "47분 전"   },
  { id: 13, postId: 62, parentId: 12,     author: "익명", text: "얘 공부는 잘하디?",                                                                            time: "44분 전"   },
  { id: 14, postId: 62, parentId: 13,     author: "익명", text: "쟤 첫룸멘데 공부는 진짜잘함 아니 면학실 자리 생기자마자 계속 심심자뜀",                        time: "41분 전"   },

  /* ── 63: 아이패드 비번 ───────────────────────────── */
  { id: 15, postId: 63,                   author: "익명", text: "찐임?",                                                                                        time: "1시간 전"  },
  { id: 16, postId: 63,                   author: "익명", text: "구라 ㄴ",                                                                                      time: "59분 전"   },
  { id: 17, postId: 63,                   author: "익명", text: "바로 갤러리부터 들어가ㅋㅋㅋㅋㅋ",                                                             time: "57분 전"   },

  /* ── 64: 책-지피티 ───────────────────────────────── */
  { id: 18, postId: 64,                   author: "익명",         text: "시험기간인데 많이 힘드냐",                                                             time: "30분 전"   },
  { id: 19, postId: 64, parentId: 18,     author: "해당글작성자", text: "ㅈㅅ 지피티가 내 말 안들어서 그냥 뻘글쓰러옴",                                        time: "28분 전"   },

  /* ── 65: 전설의 문제 ─────────────────────────────── */
  { id: 20, postId: 65,                   author: "익명", text: "이거풀면 어따써먹는데",                                                                        time: "2시간 전"  },
  { id: 21, postId: 65, parentId: 20,     author: "익명", text: "혹시모름? 이걸로 세상의 진리를 알게 될수도 있잖음;;;;;;;;;",                                  time: "1시간 전"  },

  /* ── 9102: 패드 비번 ─────────────────────────────── */
  { id: 22, postId: 9102,                 author: "익명", text: "작년에 걔한테 듣기로는 1/7이라나 뭐라나. 하여간 ㅈㄹ도 정도껏이지.",                         time: "방금 전"   },

  /* ── 9103: 책 표지 플라스틱 ──────────────────────── */
  { id: 23, postId: 9103,                 author: "익명", text: "무슨 플라스틱으로 책을 만드냐 ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그냥 착각이겠지",                    time: "방금 전"   },
];

/* ── 공개 채팅 (사이드바용 더미) ─────────────────────── */
const publicChat = [
  { author: "ㅇㅇ",        text: "오늘 저녁 급식 뭐였지?",  time: "방금 전" },
  { author: "한찌.com러",  text: "자습실 자리 남아있나",     time: "1분 전"  },
  { author: "익명",        text: "비 온다 우산 챙겨",         time: "2분 전"  },
  { author: "고양이편",    text: "고양이 봤다 ㅋㅋ",         time: "3분 전"  },
  { author: "Beta",        text: "오늘도 다들 고생했다",      time: "5분 전"  },
];
